var  faqImg 
function preload()
{
	faqImg = createImg("Images/FAQ.jpg")
	
}
function setup()
{
   createCanvas(displayWidth -48 , displayHeight-201)	
   background("lightblue")
   faqImg.position(600,13)
   faqImg.size(150 , 100)
}
function draw()
{
   textSize(20)
   fill("red")
   stroke("red")
   text("Q1) What has been the role of goverment in keeping India clean ? " , 10 , 140 )
   textSize(20)
   fill("blue")
   stroke("blue")
   text("Ans1) The Indian Goverment have launched a scheme called : Swachh Bharat Abhiyan . This campain was launched on 2nd October 2014 on Gandhi Jayanti. The " , 10 , 170)
   fill("blue")
   stroke("blue")
   text("campaign aims to achieve the vision of a 'Clean India' by 2nd October 2019. The Swachh Bharat Abhiyan is the most significant cleanliness campaign by the government" , 10, 200)
   fill("black")
   stroke("black")
   text("FEW QUESTION REGARDING SWACHH BHARAT ABHIYAN 👇" , 530 , 250)
   fill("red")
   stroke("red")
   text(" Q2) What is the main aim of Clean India Mission / Swachh Bharat Abhiyan ?" , 10 , 290)
   fill("blue")
   stroke("blue")
   text("Ans2) The mission aims to achieve universal sanitation coverage and to encourage hygienic sanitation practice. " , 10 , 320)
   fill("red")
   stroke("red")
   text("Q3) What are the Rural Sanitation programmes implemented by Ministry of Drinking Water and Sanitation (MoDWS) ?" , 10 , 360)
   fill("blue")
   stroke("blue")
   text("Ans3) The Swachh Bharat Mission (Gramin) launched on 2nd October, 2014, by modifying the erstwhile Nirmal Bharat Abhiyan (NBA), is a community-led and people-", 10 , 400 )
   fill("blue")
   stroke("blue")
   text("oriented programme aimed at universalizing safe sanitation. Swachh Bharat Mission (Gramin) is only sanitation programme implemented by Ministry of Drinking Water " ,10 , 430 )
   fill("blue")
   stroke("blue")
   text("and Sanitation" , 10 , 460)
   fill("red")
   stroke("red")
   text("Q4) What are the main activities that are carried out under the Swachh Bharat Mission? " , 10 , 490)
   fill("blue")
   stroke("blue")
   text("Ans4) The main activities are :" , 10 , 520)  
   fill("blue")
   stroke("blue")
   text("> Construction of Individual Household Latrines (IHHL)" , 10 , 550)
   fill("blue")
   stroke("blue")
   text("> Information, Education and Communication (IEC) and Human Resource Development (HRD) activities." , 10 , 580)
   fill("blue")
   stroke("blue")
   text("> Construction of Community Sanitary Complexes (CSCs)." , 10 , 610)
   fill("blue")
   stroke("blue")
   text("> Solid Liquid Waste Management (SLWM) activities" , 10 , 640)

}

